version: '3.8'

services:
  ms-usuarios:
    build: .
    container_name: navium-ms-usuarios
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      # Configuraciones del proyecto
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true