spring.application.name=ms-usuarios
server.port=8081

spring.datasource.url=jdbc:postgresql://navium-db-central.c3wswcuwyhon.us-east-1.rds.amazonaws.com:5432/navium_db
spring.datasource.username=postgres
spring.datasource.password=naviumDB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Clave secreta para firmar y validar los JWT
jwt.secret=NaviumSuperSecretKeyParaFirmaDeTokens2026